server:
  port: 8083

spring:
  application:
    name: api-gateway
#  zipkin:
#    base-url: http://localhost:9411
  config:
    import: optional:configserver:http://localhost:8084
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER #load balancer for customer|| without ms name
          predicates:
            - Path=/api/v1/customers/** #if statement to match path
            - Method=GET,POST,DELETE,PUT #if statement to match VERB
#            - Header=Authorization, Bearer (.*) #for security before accessing ms
#            - Path=/api/v1/customers/** #if statement to match path
#          filters:
#            - RewritePath=/customer/(?<segment>.*), /$\{segment}
      discovery: #with ms name
        locator:
          enabled: true
          lower-case-service-id: true
    bus:
      enabled: true
      refresh:
        enabled: true
      env:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

#actuator security
management:
  endpoint:
    info:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
#          - busrefresh
#          - busenv
#bus:
#  enabled: true
#  refresh:
#    enabled: true
#  env:
#    enabled: true